// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {time} from '../models';

export function GetCurrentState():Promise<string>;

export function GetRemainingTime():Promise<number>;

export function OnSessionEnd(arg1:domain.Session):Promise<void>;

export function OnSessionPause(arg1:domain.Session):Promise<void>;

export function OnSessionResume(arg1:domain.Session):Promise<void>;

export function OnSessionStart(arg1:domain.Session):Promise<void>;

export function OnTimerTick(arg1:domain.Session,arg2:time.Duration):Promise<void>;

export function OnWarning(arg1:time.Duration):Promise<void>;

export function PauseSession():Promise<void>;

export function ResumeSession():Promise<void>;

export function StartBreakSession():Promise<void>;

export function StartWorkSession():Promise<void>;
