// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentState() {
  return window['go']['main']['App']['GetCurrentState']();
}

export function GetRemainingTime() {
  return window['go']['main']['App']['GetRemainingTime']();
}

export function OnSessionEnd(arg1) {
  return window['go']['main']['App']['OnSessionEnd'](arg1);
}

export function OnSessionPause(arg1) {
  return window['go']['main']['App']['OnSessionPause'](arg1);
}

export function OnSessionResume(arg1) {
  return window['go']['main']['App']['OnSessionResume'](arg1);
}

export function OnSessionStart(arg1) {
  return window['go']['main']['App']['OnSessionStart'](arg1);
}

export function OnTimerTick(arg1, arg2) {
  return window['go']['main']['App']['OnTimerTick'](arg1, arg2);
}

export function OnWarning(arg1) {
  return window['go']['main']['App']['OnWarning'](arg1);
}

export function PauseSession() {
  return window['go']['main']['App']['PauseSession']();
}

export function ResumeSession() {
  return window['go']['main']['App']['ResumeSession']();
}

export function StartBreakSession() {
  return window['go']['main']['App']['StartBreakSession']();
}

export function StartWorkSession() {
  return window['go']['main']['App']['StartWorkSession']();
}
